// CAPS syllabus topics per subject, keyed by subject name matching QuizResult.subject
export const CAPS_TOPICS = {
  Mathematics: [
    'Algebra & Expressions',
    'Equations & Inequalities',
    'Number Patterns',
    'Analytical Geometry',
    'Functions & Graphs',
    'Trigonometry',
    'Euclidean Geometry',
    'Measurement',
    'Statistics & Probability',
    'Calculus',
  ],
  'Mathematical Literacy': [
    'Numbers & Operations',
    'Patterns & Relationships',
    'Finance & Interest',
    'Measurement',
    'Maps & Plans',
    'Data Handling',
    'Probability',
  ],
  'Physical Sciences': [
    'Mechanics & Motion',
    'Waves, Sound & Light',
    'Electricity & Magnetism',
    'Matter & Materials',
    'Chemical Change',
    'Chemical Systems',
    'Electrostatics',
    'Organic Chemistry',
  ],
  'Life Sciences': [
    'Cell Biology',
    'Genetics & Inheritance',
    'Evolution',
    'Biodiversity',
    'Human Physiology',
    'Plant Physiology',
    'Ecology & Environment',
    'Reproduction',
  ],
  Accounting: [
    'Accounting Equation',
    'Journals & Ledgers',
    'Bank Reconciliation',
    'Debtors & Creditors',
    'Financial Statements',
    'Partnerships',
    'Companies & VAT',
    'Budgeting & Cash Flow',
    'Cost Accounting',
  ],
  'Business Studies': [
    'Business Environments',
    'Entrepreneurship',
    'Business Ventures',
    'Business Roles',
    'Marketing',
    'Financial Management',
    'Human Resources',
    'Operations Management',
  ],
  Economics: [
    'Basic Economic Concepts',
    'Supply & Demand',
    'Market Structures',
    'Public Sector',
    'Macro-economic Goals',
    'Inflation & Unemployment',
    'Trade & International Economics',
    'Development Economics',
  ],
  History: [
    'Colonialism & Resistance',
    'The World Wars',
    'Cold War',
    'Apartheid & Resistance',
    'Liberation Movements',
    'Post-Apartheid SA',
    'Civil Rights',
    'Contemporary History',
  ],
  Geography: [
    'Geomorphology',
    'Climate & Weather',
    'Water Resources',
    'Biomes & Soils',
    'Population Geography',
    'Settlement & Urbanisation',
    'Development Geography',
    'Mapwork',
  ],
  'English HL': [
    'Language Structures & Conventions',
    'Reading & Comprehension',
    'Literature — Poetry',
    'Literature — Novel/Drama',
    'Visual Literacy',
    'Writing & Transactional Texts',
    'Oral Communication',
  ],
  'isiXhosa HL': [
    'Uqondo Lokufunda',
    'Ulwimi Nolwakhiwo',
    'Imibongo',
    'Imidlalo/Izincwadi',
    'Ukubhala',
    'Ukuthetha Nokulalela',
  ],
  'Life Orientation': [
    'Personal Development',
    'Citizenship & Democracy',
    'Career & Study Choices',
    'Health & Wellbeing',
    'Sport & Physical Activity',
    'Social & Environmental Responsibility',
  ],
  'Afrikaans HL': [
    'Taalstrukture en -konvensies',
    'Lees & Begrip',
    'Letterkunde — Poësie',
    'Letterkunde — Roman/Drama',
    'Skryfvaardighede',
    'Mondelinge Kommunikasie',
  ],
  Tourism: [
    'Tourism in SA',
    'Tourism Sectors',
    'Tourist Services',
    'Sustainable Tourism',
    'Geography of Tourism',
    'Marketing & Promotions',
    'Financial Calculations',
  ],
};