/**
 * ====================================================================
 * VIRTUAL LABORATORY COMPLIANCE LAYER
 * REFERENCE FRAMEWORK: UNIVERSITY OF COLORADO BOULDER (PhET)
 * TYPE IMPLEMENTATION: PRODUCTION STRUCTURAL INTERFACE CONTRACTS
 * ====================================================================
 */

import { SimulationType } from '@/components/SimulationCard';

// Fallback static data in case of network issues
export const STATIC_SIMULATIONS_FALLBACK: SimulationType[] = [
  {
    id: 'phet-forces-motion',
    title: 'Forces & Motion: Basics',
    subject: 'Physics',
    grade_level: 10,
    thumbnail_url: 'https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?w=400&h=250&fit=crop',
    simulation_url: 'https://phet.colorado.edu/sims/html/forces-and-motion-basics/latest/forces-and-motion-basics_en.html',
    worksheet_url: 'https://phet.colorado.edu/en/contributions/view/3460',
    description: 'Explore the forces at work when pushing a filing cabinet. Create an applied force and see how it affects motion.',
    caps_topic: 'Newton\'s Laws of Motion',
  },
  {
    id: 'phet-energy-skate',
    title: 'Energy Skate Park',
    subject: 'Physics',
    grade_level: 10,
    thumbnail_url: 'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=400&h=250&fit=crop',
    simulation_url: 'https://phet.colorado.edu/sims/html/energy-skate-park-basics/latest/energy-skate-park-basics_en.html',
    worksheet_url: 'https://phet.colorado.edu/en/contributions/view/3707',
    description: 'Learn about conservation of energy using a skate park. View the energy in the bar chart.',
    caps_topic: 'Conservation of Energy',
  },
  {
    id: 'phet-waves',
    title: 'Wave on a String',
    subject: 'Physics',
    grade_level: 11,
    thumbnail_url: 'https://images.unsplash.com/photo-1509228627152-72ae9ae6848d?w=400&h=250&fit=crop',
    simulation_url: 'https://phet.colorado.edu/sims/html/wave-on-a-string/latest/wave-on-a-string_en.html',
    worksheet_url: 'https://phet.colorado.edu/en/contributions/view/3709',
    description: 'Explore wave propagation, reflection, and interference on a string.',
    caps_topic: 'Waves, Sound and Light',
  },
  {
    id: 'phet-circuit',
    title: 'Circuit Construction Kit',
    subject: 'Physics',
    grade_level: 11,
    thumbnail_url: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=400&h=250&fit=crop',
    simulation_url: 'https://phet.colorado.edu/sims/html/circuit-construction-kit-dc/latest/circuit-construction-kit-dc_en.html',
    worksheet_url: 'https://phet.colorado.edu/en/contributions/view/3908',
    description: 'Build circuits with resistors, light bulbs, batteries, and switches.',
    caps_topic: 'Electric Circuits',
  },
  {
    id: 'phet-photoelectric',
    title: 'Photoelectric Effect',
    subject: 'Physics',
    grade_level: 12,
    thumbnail_url: 'https://images.unsplash.com/photo-1534224039826-c7a0eda0e6b3?w=400&h=250&fit=crop',
    simulation_url: 'https://phet.colorado.edu/sims/html/photoelectric-effect/latest/photoelectric-effect_en.html',
    worksheet_url: 'https://phet.colorado.edu/en/contributions/view/3916',
    description: 'See how light knocks electrons off a metal surface and explore the quantum nature of light.',
    caps_topic: 'Photoelectric Effect',
  },
  {
    id: 'phet-molecules-shapes',
    title: 'Molecule Shapes',
    subject: 'Chemistry',
    grade_level: 11,
    thumbnail_url: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=400&h=250&fit=crop',
    simulation_url: 'https://phet.colorado.edu/sims/html/molecule-shapes/latest/molecule-shapes_en.html',
    worksheet_url: 'https://phet.colorado.edu/en/contributions/view/3711',
    description: 'Explore molecular geometry by building molecules in 3D.',
    caps_topic: 'Chemical Bonding',
  },
  {
    id: 'phet-states-matter',
    title: 'States of Matter',
    subject: 'Chemistry',
    grade_level: 10,
    thumbnail_url: 'https://images.unsplash.com/photo-1562077981-4d7eafd44932?w=400&h=250&fit=crop',
    simulation_url: 'https://phet.colorado.edu/sims/html/states-of-matter/latest/states-of-matter_en.html',
    worksheet_url: 'https://phet.colorado.edu/en/contributions/view/3713',
    description: 'Examine the properties of three states of matter and phase transitions.',
    caps_topic: 'Kinetic Molecular Theory',
  },
  {
    id: 'phet-reactions-rates',
    title: 'Reactions & Rates',
    subject: 'Chemistry',
    grade_level: 12,
    thumbnail_url: 'https://images.unsplash.com/photo-1603126857599-f6e157fa2fe6?w=400&h=250&fit=crop',
    simulation_url: 'https://phet.colorado.edu/sims/html/reactions-and-rates/latest/reactions-and-rates_en.html',
    worksheet_url: 'https://phet.colorado.edu/en/contributions/view/3726',
    description: 'Explore how reactions occur and how factors affect rates of reactions.',
    caps_topic: 'Chemical Equilibrium',
  },
  {
    id: 'phet-ph-scale',
    title: 'pH Scale',
    subject: 'Chemistry',
    grade_level: 11,
    thumbnail_url: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?w=400&h=250&fit=crop',
    simulation_url: 'https://phet.colorado.edu/sims/html/ph-scale/latest/ph-scale_en.html',
    worksheet_url: 'https://phet.colorado.edu/en/contributions/view/3721',
    description: 'Test the pH of common solutions and learn about acidic and basic properties.',
    caps_topic: 'Acids and Bases',
  },
  {
    id: 'phet-natural-selection',
    title: 'Natural Selection',
    subject: 'Biology',
    grade_level: 12,
    thumbnail_url: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=400&h=250&fit=crop',
    simulation_url: 'https://phet.colorado.edu/sims/html/natural-selection/latest/natural-selection_en.html',
    worksheet_url: 'https://phet.colorado.edu/en/contributions/view/3896',
    description: 'Explore natural selection by controlling the environment and describing the bunnies\' evolution.',
    caps_topic: 'Evolution',
  },
  {
    id: 'phet-membrane-channels',
    title: 'Membrane Channels',
    subject: 'Biology',
    grade_level: 11,
    thumbnail_url: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=400&h=250&fit=crop',
    simulation_url: 'https://phet.colorado.edu/sims/html/neuron/latest/neuron_en.html',
    worksheet_url: 'https://phet.colorado.edu/en/contributions/view/3897',
    description: 'Explore how ions pass through membrane channels and generate action potentials.',
    caps_topic: 'Nervous System',
  },
  {
    id: 'phet-gene-expression',
    title: 'Gene Expression Essentials',
    subject: 'Biology',
    grade_level: 12,
    thumbnail_url: 'https://images.unsplash.com/photo-1530026186672-2cd00ffc50fe?w=400&h=250&fit=crop',
    simulation_url: 'https://phet.colorado.edu/sims/html/gene-expression-essentials/latest/gene-expression-essentials_en.html',
    worksheet_url: 'https://phet.colorado.edu/en/contributions/view/3899',
    description: 'Explore how genes are expressed through transcription and translation.',
    caps_topic: 'DNA & RNA',
  },
];

export const SUBJECTS_SIM = ['All', 'Physics', 'Chemistry', 'Biology'];
export const GRADES_SIM = ['All Grades', 'Grade 10', 'Grade 11', 'Grade 12'];
