export const SIMULATIONS = [
  // Physics
  {
    id: 'phet-forces-motion',
    title: 'Forces & Motion: Basics',
    subject: 'Physics',
    topic: 'Newton\'s Laws',
    grade: 'Grade 10',
    thumbnail: 'https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?w=400&h=250&fit=crop',
    embedUrl: 'https://phet.colorado.edu/sims/html/forces-and-motion-basics/latest/forces-and-motion-basics_en.html',
    worksheetUrl: 'https://phet.colorado.edu/en/contributions/view/3460',
    quizizzId: null,
    description: 'Explore the forces at work when pushing a filing cabinet. Create an applied force and see how it affects motion.',
    caps_topic: 'Newton\'s Laws of Motion',
  },
  {
    id: 'phet-energy-skate',
    title: 'Energy Skate Park',
    subject: 'Physics',
    topic: 'Energy',
    grade: 'Grade 10',
    thumbnail: 'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=400&h=250&fit=crop',
    embedUrl: 'https://phet.colorado.edu/sims/html/energy-skate-park-basics/latest/energy-skate-park-basics_en.html',
    worksheetUrl: 'https://phet.colorado.edu/en/contributions/view/3707',
    quizizzId: null,
    description: 'Learn about conservation of energy using a skate park. View the energy in the bar chart.',
    caps_topic: 'Conservation of Energy',
  },
  {
    id: 'phet-waves',
    title: 'Wave on a String',
    subject: 'Physics',
    topic: 'Waves',
    grade: 'Grade 11',
    thumbnail: 'https://images.unsplash.com/photo-1509228627152-72ae9ae6848d?w=400&h=250&fit=crop',
    embedUrl: 'https://phet.colorado.edu/sims/html/wave-on-a-string/latest/wave-on-a-string_en.html',
    worksheetUrl: 'https://phet.colorado.edu/en/contributions/view/3709',
    quizizzId: null,
    description: 'Explore wave propagation, reflection, and interference on a string.',
    caps_topic: 'Waves, Sound and Light',
  },
  {
    id: 'phet-circuit',
    title: 'Circuit Construction Kit',
    subject: 'Physics',
    topic: 'Electricity',
    grade: 'Grade 11',
    thumbnail: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=400&h=250&fit=crop',
    embedUrl: 'https://phet.colorado.edu/sims/html/circuit-construction-kit-dc/latest/circuit-construction-kit-dc_en.html',
    worksheetUrl: 'https://phet.colorado.edu/en/contributions/view/3908',
    quizizzId: null,
    description: 'Build circuits with resistors, light bulbs, batteries, and switches.',
    caps_topic: 'Electric Circuits',
  },
  {
    id: 'phet-photoelectric',
    title: 'Photoelectric Effect',
    subject: 'Physics',
    topic: 'Modern Physics',
    grade: 'Grade 12',
    thumbnail: 'https://images.unsplash.com/photo-1534224039826-c7a0eda0e6b3?w=400&h=250&fit=crop',
    embedUrl: 'https://phet.colorado.edu/sims/html/photoelectric-effect/latest/photoelectric-effect_en.html',
    worksheetUrl: 'https://phet.colorado.edu/en/contributions/view/3916',
    quizizzId: null,
    description: 'See how light knocks electrons off a metal surface and explore the quantum nature of light.',
    caps_topic: 'Photoelectric Effect',
  },
  // Chemistry
  {
    id: 'phet-molecules-shapes',
    title: 'Molecule Shapes',
    subject: 'Chemistry',
    topic: 'Molecular Geometry',
    grade: 'Grade 11',
    thumbnail: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=400&h=250&fit=crop',
    embedUrl: 'https://phet.colorado.edu/sims/html/molecule-shapes/latest/molecule-shapes_en.html',
    worksheetUrl: 'https://phet.colorado.edu/en/contributions/view/3711',
    quizizzId: null,
    description: 'Explore molecular geometry by building molecules in 3D.',
    caps_topic: 'Chemical Bonding',
  },
  {
    id: 'phet-states-matter',
    title: 'States of Matter',
    subject: 'Chemistry',
    topic: 'Kinetic Theory',
    grade: 'Grade 10',
    thumbnail: 'https://images.unsplash.com/photo-1562077981-4d7eafd44932?w=400&h=250&fit=crop',
    embedUrl: 'https://phet.colorado.edu/sims/html/states-of-matter/latest/states-of-matter_en.html',
    worksheetUrl: 'https://phet.colorado.edu/en/contributions/view/3713',
    quizizzId: null,
    description: 'Examine the properties of three states of matter and phase transitions.',
    caps_topic: 'Kinetic Molecular Theory',
  },
  {
    id: 'phet-reactions-rates',
    title: 'Reactions & Rates',
    subject: 'Chemistry',
    topic: 'Chemical Kinetics',
    grade: 'Grade 12',
    thumbnail: 'https://images.unsplash.com/photo-1603126857599-f6e157fa2fe6?w=400&h=250&fit=crop',
    embedUrl: 'https://phet.colorado.edu/sims/html/reactions-and-rates/latest/reactions-and-rates_en.html',
    worksheetUrl: 'https://phet.colorado.edu/en/contributions/view/3726',
    quizizzId: null,
    description: 'Explore how reactions occur and how factors affect rates of reactions.',
    caps_topic: 'Chemical Equilibrium',
  },
  {
    id: 'phet-ph-scale',
    title: 'pH Scale',
    subject: 'Chemistry',
    topic: 'Acids & Bases',
    grade: 'Grade 11',
    thumbnail: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?w=400&h=250&fit=crop',
    embedUrl: 'https://phet.colorado.edu/sims/html/ph-scale/latest/ph-scale_en.html',
    worksheetUrl: 'https://phet.colorado.edu/en/contributions/view/3721',
    quizizzId: null,
    description: 'Test the pH of common solutions and learn about acidic and basic properties.',
    caps_topic: 'Acids and Bases',
  },
  // Biology
  {
    id: 'phet-natural-selection',
    title: 'Natural Selection',
    subject: 'Biology',
    topic: 'Evolution',
    grade: 'Grade 12',
    thumbnail: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=400&h=250&fit=crop',
    embedUrl: 'https://phet.colorado.edu/sims/html/natural-selection/latest/natural-selection_en.html',
    worksheetUrl: 'https://phet.colorado.edu/en/contributions/view/3896',
    quizizzId: null,
    description: 'Explore natural selection by controlling the environment and describing the bunnies\' evolution.',
    caps_topic: 'Evolution',
  },
  {
    id: 'phet-membrane-channels',
    title: 'Membrane Channels',
    subject: 'Biology',
    topic: 'Cell Biology',
    grade: 'Grade 11',
    thumbnail: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=400&h=250&fit=crop',
    embedUrl: 'https://phet.colorado.edu/sims/html/neuron/latest/neuron_en.html',
    worksheetUrl: 'https://phet.colorado.edu/en/contributions/view/3897',
    quizizzId: null,
    description: 'Explore how ions pass through membrane channels and generate action potentials.',
    caps_topic: 'Nervous System',
  },
  {
    id: 'phet-gene-expression',
    title: 'Gene Expression Essentials',
    subject: 'Biology',
    topic: 'Genetics',
    grade: 'Grade 12',
    thumbnail: 'https://images.unsplash.com/photo-1530026186672-2cd00ffc50fe?w=400&h=250&fit=crop',
    embedUrl: 'https://phet.colorado.edu/sims/html/gene-expression-essentials/latest/gene-expression-essentials_en.html',
    worksheetUrl: 'https://phet.colorado.edu/en/contributions/view/3899',
    quizizzId: null,
    description: 'Explore how genes are expressed through transcription and translation.',
    caps_topic: 'DNA & RNA',
  },
];

export const SUBJECTS_SIM = ['All', 'Physics', 'Chemistry', 'Biology'];
export const GRADES_SIM = ['All Grades', 'Grade 10', 'Grade 11', 'Grade 12'];